# Generated by Django 2.1.5 on 2019-03-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comment_text', models.CharField(max_length=200)),
                ('comment_author', models.CharField(max_length=30, null=True)),
                ('comment_publish_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'db_table': 'application_comments',
            },
        ),
    ]
